from __future__ import annotations

import json
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "enrichment" / "hubei_inventory.json"

S = {
    "whfzg_gongyezhi_hubei_dianji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》湖北电机厂节（1958年组建武汉综合电机厂、1967年更名）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371036.html",
        "authority": "A",
        "notes": "1958年10月由新中、大华等电机厂合并为武汉综合电机厂，迁关山建厂，1967年更名湖北电机厂；全国中小型电机重点专业厂之一、湖北省最大的电机生产厂。全文核读。",
    },
    "whfzg_gongyezhi_weixing_dianji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》武汉微型电机厂节（1942年建华电机厂起源，1969年定名）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371037.html",
        "authority": "A",
        "notes": "前身1942年陈建华创汉口建华电机厂，1969年改名武汉微型电机厂，1971年迁关山；分马力电机至1985年累计出口32029台，隔爆电机填补国内空白。全文核读。",
    },
    "whfzg_gongyezhi_qilun_fadianji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》汽轮发电机节（1958年组建，中南第一座电站汽轮机制造厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371050.html",
        "authority": "A",
        "notes": "1958年5月由武汉动力机厂与永华电机厂合并组建，1959年迁关山；中南地区第一座电站汽轮机、汽轮发电机制造厂，全国六大电站汽轮发电机制造企业之一，1970年定名武汉汽轮发电机厂。全文核读。",
    },
    "whfzg_gongyezhi_tuolaji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》拖拉机节（武汉拖拉机厂沿革；同节载武汉柴油机厂、湖北柴油机厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/370998.html",
        "authority": "A",
        "notes": "1964年以武汉小型拖拉机厂等为主机厂，1966年10月更名武汉拖拉机厂，工农-7型累计生产13098台，工农-12型1979年年产15037台，1984年获机械部优质产品；同节另载武汉柴油机厂（国内第一台手扶拖拉机，已另条在册HBI-WUHAN-034）与湖北柴油机厂（已另条在册HBI-PROV-010）。全文核读。",
    },
    "whfzg_gongyezhi_neiranji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》武汉内燃机厂节（1956年建厂，中速柴油机定点厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371004.html",
        "authority": "A",
        "notes": "1956年建厂（省公安厅劳改局），1964年划归农机部定为中速柴油机厂；4160型柴油机1979年产8.31万马力超设计能力，1971年曾产8V160坦克发动机（704产品）。全文核读。",
    },
    "whfzg_gongyezhi_zhoucheng": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》轴承节（1958年关山建国营武汉轴承厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371056.html",
        "authority": "A",
        "notes": "1958年6月在关山兴建国营武汉轴承厂（武汉首家专业滚动轴承厂），1969年12月重建，1973年成一机部定点厂，1983年产品填补国内空白；同节另载武汉第二轴承厂（1970年，汉阳琴断口）、武汉钢球厂（1971年）线索待后续核查。全文核读。",
    },
    "whfzg_gongyezhi_biaozhunjin": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》标准紧固件节（1958年建厂、1965年总厂辖14个专业厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371057.html",
        "authority": "A",
        "notes": "行业肇端1895年周恒顺炉冶坊手工制螺丝；1958年12月成立武汉国营机械标准件厂，1962年改名武汉标准件厂，1965年设武汉标准件总厂辖14个专业厂，1982年年产35939万件。全文核读。",
    },
    "whfzg_gongyezhi_qizhongji": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》起重机节（1972年定名武汉起重机厂，机械部定点重点厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371016.html",
        "authority": "A",
        "notes": "1972年1月武汉铸造设备厂并入武汉第二通用机械厂正式改名武汉起重机厂；1970-1985年产各类起重机械2471台，16吨双梁吊填补国内空白。全文核读。",
    },
    "whfzg_gongyezhi_qiangpaochang": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》专记·湖北枪炮厂（1890年张之洞移厂就鄂，'汉阳造'发源地）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371079.html",
        "authority": "A",
        "notes": "光绪十六年（1890）张之洞'移厂就鄂'建于汉阳龟山北麓，产'汉阳造'79步枪，至1909年造枪130658支、炮986门；1904年改湖北兵工厂，1908年改汉阳兵工厂，1938年西迁，1947年留汉部分改第三十兵工厂（另见371083节）。全文核读。",
    },
    "whfzg_gongyezhi_yangzi_qixie": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》专记·扬子机器厂（1907年创办于汉口谌家矶，六大部）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371086.html",
        "authority": "A",
        "notes": "1907年7月李维格、宋炜臣、王光等集资35万两创办于汉口谌家矶，设化铁、机器、电机、翻砂、桥梁、造船六大部，承造建中、永安、拱辰三舰；1918年改组扬子机器公司并入汉冶萍，1922年转让为六河沟铁厂。全文核读。",
    },
    "whfzg_gongyezhi_zhouhengshun": {
        "source_type": "local_gazetteer_official",
        "title": "《武汉市志·工业志》专记·周恒顺机器厂（1866年炉冶坊起源，三镇最长民营机器厂）",
        "org": "武汉地方志数字方志馆",
        "pub_date": None,
        "url": "https://www.whfzg.org.cn/book/dfz/bookread/id/1003/category_id/371087.html",
        "authority": "A",
        "notes": "1866年周氏炉冶坊迁汉阳双街，1905年改名周恒顺机器厂，三镇历史最长、规模最大的民营机器厂，产轧花机、蒸汽机、蒸汽起重机、造币机、小火轮；1952年改国营中南动力机制造厂，1956年武汉动力机厂，1958年武汉汽轮机厂，1966年武汉第二机床厂。全文核读。",
    },
    "whjcc_official": {
        "source_type": "enterprise_official_site",
        "title": "武汉机床有限责任公司官网公司简介（1928年阮恒昌机器制造厂起源，1951年定名）",
        "org": "武汉机床有限责任公司",
        "pub_date": None,
        "url": "https://www.whjcc1951.com/",
        "authority": "B",
        "notes": "始建于1928年（阮恒昌机器制造厂），1951年武汉市接管合并更名武汉机床厂，机床行业'十八罗汉'厂之一，全国生产工具刃具磨床的骨干企业，2013年改制并入武汉产投集团。官网核读。",
    },
    "zjtcn_shashi_yijichuang": {
        "source_type": "encyclopedia_entry",
        "title": "沙市第一机床厂（1956年始建，机械部重点企业，摇臂钻床三获国家金质奖）",
        "org": "造价通建设工程百科",
        "pub_date": None,
        "url": "https://www.zjtcn.com/baike/ssdyjcc7163086.html",
        "authority": "B",
        "notes": "始建于1956年，原国家机械工业部重点企业，摇臂钻床定点生产厂，Z3040×16摇臂钻床1980、1984、1989年三获国家金质奖，2003年改制为湖北机一机床公司。词条核读。",
    },
    "jznews_shashi_jichuang_2022": {
        "source_type": "official_media",
        "title": "沙市机床一厂的'巅峰岁月'（'北有中捷人民友谊厂，南有沙市机床一厂'）",
        "org": "荆州新闻网",
        "pub_date": "2022-03-16",
        "url": "http://news.jznews.com.cn/",
        "authority": "B",
        "notes": "佐证'北有中捷人民友谊厂，南有沙市机床一厂'的行业地位；原文因证书问题未能打开核读，仅搜索摘录佐证，后续需补核原文。",
    },
    "cmtba_changji_2024": {
        "source_type": "industry_association_official",
        "title": "宜昌长机科技有限责任公司（原长江机床厂/515厂，三线重点工程，新中国第一台大型插齿机诞生地）",
        "org": "中国机床工具工业协会",
        "pub_date": "2024-10-16",
        "url": "https://www.cmtba.org.cn/web/7/202501/8907.html",
        "authority": "B",
        "notes": "始建于1968年，国家'三线'建设重点工程之一，新中国第一台大型插齿机诞生地；另据阳本网企业页由始建于1969年的长江机床厂整体改制而成（两源年代相差一年，待厂志核校）。协会官网核读。",
    },
    "renben_huangshi_yuanqu": {
        "source_type": "enterprise_official_site",
        "title": "人本股份黄石园区（前身黄石轴承厂，下陆区老下陆街168号）",
        "org": "人本股份有限公司",
        "pub_date": None,
        "url": "https://www.cugroup.com/About/BaseInfo?id=37ca5fab",
        "authority": "B",
        "notes": "人本黄石园区成立于2008年，前身是黄石轴承厂，址黄石市下陆区老下陆街168号。官网核读；建厂年代官网未载待考。",
    },
    "huangshigang_chaiqian_2025": {
        "source_type": "district_government_publicity",
        "title": "黄石港区2025年公示'黄石市轴承厂'2024年获拆迁补偿款（老厂区拆迁线索）",
        "org": "黄石港区人民政府",
        "pub_date": "2025",
        "url": None,
        "authority": "A",
        "notes": "政府公示显示'黄石市轴承厂'2024年获拆迁补偿款，老厂区正处拆迁，抢救记录紧迫；此条仅搜索摘录佐证未核读原文，公示区域归属与厂区边界待函询补核。",
    },
}


def _r(rid, nm, city, dc, cat, lvl, status, src, kind, yr, mat, tech, soc, use, notes, aliases):
    return {
        "inventory_id": rid, "name": nm, "city": city, "district_county": dc,
        "industry_category_l1": cat, "recognition_level": lvl, "recognition_status": status,
        "record_status": "source_confirmed", "geocode_status": "pending", "source_keys": src,
        "cultural_evidence": {"material_carriers": mat, "technical_memory": tech, "social_memory": soc, "current_use_or_loss": use},
        "notes": notes, "aliases": aliases, "asset_kind": kind,
    }


RECORDS = [
    _r("HBI-WUHAN-079", "武汉机床厂", "武汉市", "武汉市（历史厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；企业官网与行业史志沿革（机床行业'十八罗汉'之一）",
       ["whjcc_official"], "industrial_site", "1928年（起源）/1951年（定名）",
       "工具刃具磨床产品谱系与历史厂区（现存状态待现场核验）",
       "全国生产工具刃具磨床骨干企业的磨床制造工艺记忆",
       "机床行业'十八罗汉'厂之一的行业地位与职工记忆",
       "2013年改制并入武汉产投集团，企业存续（武汉机床有限责任公司）；老厂区遗存待核",
       "官网核读（B级）；老厂区位置与遗存本体未核验，后续需厂志或档案补充；坐标未核验保持待核。",
       ["阮恒昌机器制造厂", "武汉机床有限责任公司"]),
    _r("HBI-WUHAN-080", "湖北电机厂", "武汉市", "洪山区关山（关山机电工业区）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（湖北省最大电机生产厂）",
       ["whfzg_gongyezhi_hubei_dianji"], "industrial_site", "1958年（组建）/1967年（更名）",
       "关山机电工业区电机厂区与中小型电机产品谱系（遗存待现场核验）",
       "全国中小型电机重点专业厂的电机制造工艺（湖北省最大电机生产厂）",
       "'一五'后武汉机电工业体系建设与关山工业区职工记忆",
       "厂区现状待核（关山工业区已城市化）",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体与厂址边界未核验；坐标未核验保持待核。",
       ["武汉综合电机厂"]),
    _r("HBI-WUHAN-081", "武汉微型电机厂", "武汉市", "洪山区关山（1971年迁入）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（分马力电机出口骨干）",
       ["whfzg_gongyezhi_weixing_dianji"], "industrial_site", "1942年（建华电机厂起源）/1969年（定名）",
       "分马力电机出口产品谱系（至1985年累计出口32029台）与关山厂区（遗存待核）",
       "分马力电机制造与隔爆电机技术（填补国内空白）",
       "1942年汉口建华电机厂的民营电机工业起源记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体未核验；坐标未核验保持待核。",
       ["汉口建华电机厂"]),
    _r("HBI-WUHAN-082", "武汉汽轮发电机厂", "武汉市", "洪山区关山（1959年迁入）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（中南第一座电站汽轮机制造厂）",
       ["whfzg_gongyezhi_qilun_fadianji"], "industrial_site", "1958年（组建）/1970年（定名）",
       "电站汽轮机与汽轮发电机组产品谱系及关山厂区（遗存待核）",
       "中南地区第一座电站汽轮机制造厂的汽轮发电机制造工艺（全国六大之一）",
       "1958年武汉动力机厂与永华电机厂合并组建的机电工业整合记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体未核验；坐标未核验保持待核。",
       []),
    _r("HBI-WUHAN-083", "武汉拖拉机厂", "武汉市", "武汉市（厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（工农系列手扶拖拉机主机厂）",
       ["whfzg_gongyezhi_tuolaji"], "industrial_site", "1964年（组建）/1966年（定名）",
       "工农-7型（累计13098台）与工农-12型（1979年年产15037台）手扶拖拉机产品谱系（遗存待核）",
       "手扶拖拉机批量制造工艺与1984年机械部优质产品质量记忆",
       "湖北农业机械化进程中的主机厂记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；与在册湖北省拖拉机厂（HBI-HS-016）非同一企业；遗存本体未核验；坐标未核验保持待核。",
       ["武汉小型拖拉机厂"]),
    _r("HBI-WUHAN-084", "武汉内燃机厂", "武汉市", "武汉市（厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（中速柴油机定点厂）",
       ["whfzg_gongyezhi_neiranji"], "industrial_site", "1956年（建厂）",
       "4160型中速柴油机产品谱系（1979年产8.31万马力超设计能力）与厂区（遗存待核）",
       "中速柴油机定点制造工艺；1971年8V160坦克发动机（704产品）军工记忆",
       "省公安厅劳改局建厂的特殊建厂史与农机动力供应记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体未核验；坐标未核验保持待核。",
       []),
    _r("HBI-WUHAN-085", "武汉轴承厂", "武汉市", "洪山区关山", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（武汉首家专业滚动轴承厂）",
       ["whfzg_gongyezhi_zhoucheng"], "industrial_site", "1958年（首建）/1969年（重建）",
       "滚动轴承产品谱系与关山厂区（遗存待核）",
       "武汉首家专业滚动轴承厂制造工艺；1983年产品填补国内空白",
       "1973年一机部定点厂的行业地位记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；同节武汉第二轴承厂（1970年汉阳琴断口）、武汉钢球厂（1971年）线索留待后续轮核查；坐标未核验保持待核。",
       ["国营武汉轴承厂"]),
    _r("HBI-WUHAN-086", "武汉标准件厂", "武汉市", "武汉市（厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（标准件总厂体系）",
       ["whfzg_gongyezhi_biaozhunjin"], "industrial_site", "1958年（建厂）/1965年（总厂体系）",
       "标准紧固件产品谱系（1982年年产35939万件）与总厂辖14个专业厂体系（遗存待核）",
       "从1895年周恒顺炉冶坊手工制螺丝到机械化标准件生产的工艺演进",
       "武汉标准件总厂体系与职工记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体未核验；坐标未核验保持待核。",
       ["武汉国营机械标准件厂", "武汉标准件总厂"]),
    _r("HBI-WUHAN-087", "武汉起重机厂", "武汉市", "武汉市（厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志工业志专节沿革（机械部定点重点厂）",
       ["whfzg_gongyezhi_qizhongji"], "industrial_site", "1972年（定名）",
       "各类起重机械产品谱系（1970-1985年产2471台）与厂区（遗存待核）",
       "16吨双梁吊填补国内空白的起重机械制造工艺",
       "机械工业部定点重点厂的行业记忆",
       "厂区现状待核",
       "武汉市志工业志专节核读（A级方志馆）；遗存本体未核验；坐标未核验保持待核。",
       ["武汉第二通用机械厂", "武汉铸造设备厂"]),
    _r("HBI-WUHAN-088", "湖北枪炮厂—汉阳兵工厂旧址", "武汉市", "汉阳区龟山北麓", "军事工业", "research_candidate",
       "无本体遗存法定认定；武汉市志专记与近代工业史完整沿革（'汉阳造'发源地）",
       ["whfzg_gongyezhi_qiangpaochang"], "industrial_site", "1890年（建厂）",
       "龟山北麓厂区旧址（地上遗存稀少，现状融入城市更新片区）",
       "'汉阳造'79步枪制造工艺与近代军工体系（至1909年造枪130658支、炮986门）",
       "张之洞'移厂就鄂'与湖北近代军工发端记忆；1938年西迁的抗战工业迁徙记忆",
       "原址地上遗存稀少，所在范围今为汉阳造文化创意园等城市功能（另条在册HBI-WUHAN-036）",
       "武汉市志专记核读（A级方志馆）；旧址本体遗存与文保身份未核验；与汉阳造文化创意园条目互为历史层与现状层；坐标未核验保持待核。",
       ["湖北兵工厂", "汉阳兵工厂", "第三十兵工厂"]),
    _r("HBI-WUHAN-089", "扬子机器厂旧址", "武汉市", "江岸区谌家矶", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志专记沿革（近代民营机械造船联合企业）",
       ["whfzg_gongyezhi_yangzi_qixie"], "industrial_site", "1907年（创办）",
       "谌家矶厂区旧址（化铁、机器、电机、翻砂、桥梁、造船六大部，遗存待核）",
       "承造建中、永安、拱辰三舰的近代民营造船与机器制造工艺",
       "李维格、宋炜臣、王光等集资35万两的近代民族资本创业记忆；1918年并入汉冶萍",
       "1922年转让为六河沟铁厂后厂区脉络中断，遗存待考古调查",
       "武汉市志专记核读（A级方志馆）；与在册汉冶萍诸条（HBI-WUHAN-001、HBI-HS-001）为关联但不同实体；遗存本体未核验；坐标未核验保持待核。",
       ["扬子机器公司"]),
    _r("HBI-WUHAN-090", "周恒顺机器厂", "武汉市", "汉阳区（汉阳双街）", "机械工业", "research_candidate",
       "无法定遗产认定；武汉市志专记沿革（三镇历史最长、规模最大的民营机器厂）",
       ["whfzg_gongyezhi_zhouhengshun"], "industrial_site", "1866年（起源）/1905年（改名机器厂）",
       "轧花机、蒸汽机、蒸汽起重机、造币机、小火轮产品谱系（遗存待核）",
       "从炉冶坊到机器厂的铸造与机械制造工艺演进",
       "1866年周氏炉冶坊家族工业传承与武汉民营机械工业发端记忆",
       "1952年后改组为国营厂（中南动力机—武汉动力机—武汉汽轮机—武汉第二机床厂），原厂址遗存待核",
       "武汉市志专记核读（A级方志馆）；1958年'武汉汽轮机厂'沿革与武汉汽轮发电机厂节记载交叠，厂名谱系待厂志核校；坐标未核验保持待核。",
       ["周恒顺炉冶坊"]),
    _r("HBI-JZ-078", "沙市第一机床厂", "荆州市", "沙市区（厂址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；建设工程百科与媒体专题沿革（机械部重点企业、三获国家金质奖）",
       ["zjtcn_shashi_yijichuang", "jznews_shashi_jichuang_2022"], "industrial_site", "1956年（始建）",
       "Z3040×16摇臂钻床产品谱系（1980、1984、1989年三获国家金质奖）与厂区（遗存待核）",
       "摇臂钻床定点制造工艺（'北有中捷人民友谊厂，南有沙市机床一厂'）",
       "沙市机械工业鼎盛期职工记忆与三获金质奖的行业声誉",
       "2003年改制为湖北机一机床公司，企业存续；老厂区遗存待核",
       "造价通词条核读（B级）+荆州新闻网摘录佐证（原文未核读）；与在册荆州机床厂旧址（HBI-JZ-018）非同一企业；坐标未核验保持待核。",
       ["沙市机床一厂", "湖北机一机床公司"]),
    _r("HBI-YC-070", "宜昌长江机床厂（515厂）", "宜昌市", "宜昌市（三线厂区地址待专项核验）", "机械工业", "research_candidate",
       "无法定遗产认定；机床工具行业协会企业志沿革（三线重点工程）",
       ["cmtba_changji_2024"], "industrial_site", "1968年（始建，一说1969年）",
       "大型插齿机与齿轮机床产品谱系及三线厂区（遗存待核）",
       "新中国第一台大型插齿机诞生地的齿轮机床制造工艺",
       "'三线'建设重点工程515厂的三线职工记忆",
       "整体改制为宜昌长机科技有限责任公司（现役齿轮机床企业），厂区延续使用",
       "机床工具工业协会官网核读（B级）；建厂年代两源相差一年待厂志核校；坐标未核验保持待核。",
       ["515厂", "长江机床厂", "宜昌长机科技"]),
    _r("HBI-HS-059", "黄石轴承厂老厂区", "黄石市", "下陆区老下陆街168号", "机械工业", "research_candidate",
       "无法定遗产认定；企业官网沿革与政府拆迁公示线索（老厂区拆迁中）",
       ["renben_huangshi_yuanqu", "huangshigang_chaiqian_2025"], "industrial_site", "建厂年代待考（2008年人本黄石园区接续）",
       "下陆老厂区建筑与轴承生产线遗存（拆迁中，抢救记录紧迫）",
       "黄石轴承制造工艺在人本体系内的接续（2008年至今）",
       "老下陆工业区轴承工人记忆",
       "老厂区正处拆迁（2024年获拆迁补偿款公示线索），抢救记录紧迫",
       "人本官网核读（B级）确认前身与地址；拆迁信息仅政府公示搜索摘录未核读原文，区域归属待核；建厂年代待厂志补考；坐标未核验保持待核。",
       ["黄石市轴承厂", "人本黄石园区"]),
]


def main():
    data = json.loads(PATH.read_text(encoding="utf-8"))
    sources = data.setdefault("sources", {})
    records = data.setdefault("records", [])
    for key, source in S.items():
        if key in sources and sources[key] != source:
            raise SystemExit(f"conflicting source: {key}")
    sources.update(S)
    added = 0
    for record in RECORDS:
        existing = next((r for r in records if r["inventory_id"] == record["inventory_id"]), None)
        if existing is not None:
            if existing != record:
                raise SystemExit(f"conflicting duplicate record: {record['inventory_id']}")
            continue
        if any(r["name"] == record["name"] for r in records):
            raise SystemExit(f"conflicting duplicate name: {record['name']}")
        records.append(record)
        added += 1
    PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wave_dk_S={len(S)} added={added} total={len(records)} src={len(sources)}")


if __name__ == "__main__":
    main()
